### ISSUE TITLE
Written statement of ownership transfer

### ISSUE THREAD

**Issue by ianfowler** [titanscout2022/red-alliance-mobile#17]
red-alliance-mobile and its derivatives managed by the titanscouting2022 team, formerly the intellectual property of myself (Ian Fowler) and those directly working on the project, is now intellectual property of Titan Robotics, FRC Team 2022. This software is to be managed by the head of titan scouting and is to receive oversight by the captains of Titan Robotics. I, Ian Fowler, hold no rights to this software.

**Comment by devksingh4** [comment]
Documentation received. Closing issue.
